name: my_flutter_project
description: A new Flutter project
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

  # Add other dependencies here
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Add other dev dependencies here
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
   # - assets/images/

  # Add fonts here
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
